/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExamenParcial1.view;

/**
 *
 * @author Gerardo Cabrera
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWIndow
     */
    public MainWindow() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bMaterias = new javax.swing.JButton();
        bAlumnos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bMaterias.setText("Materias");
        bMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMateriasActionPerformed(evt);
            }
        });
        getContentPane().add(bMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 210, 220));

        bAlumnos.setText("Alumnos");
        bAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlumnosActionPerformed(evt);
            }
        });
        getContentPane().add(bAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAlumnosActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        
        AlumnosWindow window = new AlumnosWindow();
        window.setVisible(true);
        
    }//GEN-LAST:event_bAlumnosActionPerformed

    private void bMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMateriasActionPerformed
        // TODO add your handling code here:
        
        MateriasWindow window = new MateriasWindow();
        window.setVisible(true);
    }//GEN-LAST:event_bMateriasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlumnos;
    private javax.swing.JButton bMaterias;
    // End of variables declaration//GEN-END:variables
}
