/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ExamenParcial1.view;

import ExamenParcial1.buisnesslogic.StudentBLO;
import ExamenParcial1.buisnesslogic.SubjectBLO;
import ExamenParcial1.model.Student;
import ExamenParcial1.model.Subject;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gerardo Cabrera
 */
public class MateriasWindow extends javax.swing.JFrame {

    /**
     * Creates new form Materias
     */
    
    StudentBLO studentBLO = new StudentBLO();
    SubjectBLO subjectBLO = new SubjectBLO();
    List<String> nombresMaterias = new ArrayList<>();
    
    public MateriasWindow() {
        initComponents();
        setLocationRelativeTo(null);
        studentBLO.load();
        
        subjectBLO.load();
        for(int i = 0; i < subjectBLO.findAll().size(); i++)
        {
            nombresMaterias.add(subjectBLO.findAll().get(i).getNombre());
        }
        
        cbMaterias.setModel(new DefaultComboBoxModel(nombresMaterias.toArray()));
        
        String materia = (String) cbMaterias.getSelectedItem();
        tfDocente.setText(subjectBLO.findByName(materia).get(0).getDocente());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cbMaterias = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tfDocente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterias = new javax.swing.JTable();
        bRefresh = new javax.swing.JButton();
        bUpdate = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlumnos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bExit.setText("Save & Exit");
        bExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExitActionPerformed(evt);
            }
        });
        getContentPane().add(bExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 40));

        jLabel1.setText("Materia:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        cbMaterias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMateriasItemStateChanged(evt);
            }
        });
        getContentPane().add(cbMaterias, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 110, -1));

        jLabel2.setText("Docente:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));
        getContentPane().add(tfDocente, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 110, -1));

        tblMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Docente"
            }
        ));
        tblMaterias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMateriasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMaterias);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 380, 170));

        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(bRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 690, 50));

        bUpdate.setText("Update");
        bUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(bUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 130, 40));

        tblAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CURP", "Nombre(s)", "Apellido(s)", "Fecha de Nacimiento", "Género", "Estado"
            }
        ));
        tblAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAlumnosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAlumnos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 670, 240));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMateriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMateriasItemStateChanged
        // TODO add your handling code here:
        String materia = (String) cbMaterias.getSelectedItem();
        tfDocente.setText(subjectBLO.findByName(materia).get(0).getDocente());
    }//GEN-LAST:event_cbMateriasItemStateChanged

    private void bUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUpdateActionPerformed
        // TODO add your handling code here:
        String materia = (String) cbMaterias.getSelectedItem();
        String docente = tfDocente.getText();
        Subject subject = subjectBLO.findByName(materia).get(0);
        
        
        List<Student> studentList = studentBLO.findAll();
        
        for(int i = 0; i < studentList.size(); i++)
        {
            List<Subject> subjects = studentList.get(i).getMaterias();
            for(int j = 0; j < subjects.size(); j++)
            {
            if(subjects.get(j).getNombre().equals(subject.getNombre()))
                {
                    subjects.get(j).setDocente(docente);
                }
            }
        }
        
        subject.setDocente(docente);
        subjectBLO.update(subject);
    }//GEN-LAST:event_bUpdateActionPerformed

    private void bExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExitActionPerformed
        // TODO add your handling code here:
        studentBLO.commitChanges();
        subjectBLO.commitChanges();
        this.dispose();
        
        MainWindow window = new MainWindow();
        window.setVisible(true);
    }//GEN-LAST:event_bExitActionPerformed

    private void tblAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAlumnosMouseClicked
        // TODO add your handling code here:

        DefaultTableModel dtm = (DefaultTableModel) tblAlumnos.getModel();
        int selectedRowIndex = tblAlumnos.getSelectedRow();
        
    }//GEN-LAST:event_tblAlumnosMouseClicked

    private void tblMateriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMateriasMouseClicked
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblMaterias.getModel();
        int selectedRowIndex = tblMaterias.getSelectedRow();
        String nombre = (String) dtm.getValueAt(selectedRowIndex, 0);
        Subject subject = subjectBLO.findByName(nombre).get(0);
        
        List<Student> studentList = subject.getAlumnos();
        
        refreshTable(studentList);
    }//GEN-LAST:event_tblMateriasMouseClicked

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        // TODO add your handling code here:
        refreshSubjectsTable(subjectBLO.findAll());
    }//GEN-LAST:event_bRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MateriasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MateriasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MateriasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MateriasWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MateriasWindow().setVisible(true);
            }
        });
    }

    private void refreshTable(List<Student> studentList)
    {
        clearTable();
        
        DefaultTableModel dtm = (DefaultTableModel) tblAlumnos.getModel();
        Object[] emptyRow = {""};
        
        for (int i = 0; i < studentList.size(); i++) {
            dtm.addRow(emptyRow);
            dtm.setValueAt(studentList.get(i).getCurp(), i, 0);
            dtm.setValueAt(studentList.get(i).getNombre() + " " + studentList.get(i).getSegundoNombre() , i, 1);
            dtm.setValueAt(studentList.get(i).getApellidoPaterno() + " " + studentList.get(i).getApellidoMaterno() , i, 2);
            dtm.setValueAt(studentList.get(i).getFechaNacimiento(), i, 3);
            dtm.setValueAt(studentList.get(i).getSexo(), i, 4);
            dtm.setValueAt(studentList.get(i).getEstado(), i, 5);
        }
    }
    
    private void refreshSubjectsTable(List<Subject> subjectList)
    {
        clearSubjectsTable();
        
        DefaultTableModel dtm = (DefaultTableModel) tblMaterias.getModel();
        Object[] emptyRow = {""};
        
        for (int i = 0; i < subjectList.size(); i++) {
            dtm.addRow(emptyRow);
            dtm.setValueAt(subjectList.get(i).getNombre(), i, 0);
            dtm.setValueAt(subjectList.get(i).getDocente(), i, 1);
        }
    }
    
    private void clearTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) tblAlumnos.getModel();
        while(dtm.getRowCount()>0)
        {
            dtm.removeRow(0);
        }
    }
    
        private void clearSubjectsTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) tblMaterias.getModel();
        while(dtm.getRowCount()>0)
        {
            dtm.removeRow(0);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExit;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bUpdate;
    private javax.swing.JComboBox<String> cbMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAlumnos;
    private javax.swing.JTable tblMaterias;
    private javax.swing.JTextField tfDocente;
    // End of variables declaration//GEN-END:variables
}
